# docker-compose.yml
services:
  postgres:
    image: postgres:15
    container_name: digital-pharmacy-db
    environment:
      POSTGRES_DB: digital_pharmacy
      POSTGRES_USER: pharmacy_user
      POSTGRES_PASSWORD: pharmacy_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: